### ISSUE TITLE
Extend get_object_set function to retrieve additional free fields using EcoTaxa API

### ISSUE THREAD

**Issue by mdugenne** [ecotaxa/ecotaxa_py_client#5]
Would it be possible to extend (or create  new function(s) as part of Project,Process,SampleApi) the fields allowed and returned by the function get_object_set?
At the moment, it only allows fields related to objects (i.e. classification, image , free fields from classified field list) but I am interested in getting additional free fields (e.g. sample volume analyzed, mesh size, etc.) which aren't necessarily part of the classified list.
Thank you

**Comment by juliecoust** [comment]
This evolution should be done directly on ecotaxa_back repository
