### ISSUE TITLE
Including timestamp for latest update in ProjectModel

### ISSUE THREAD

**Issue by mdugenne** [ecotaxa/ecotaxa_py_client#6]
Would it be possible to include the timestamp of the last modifications applied to a project in ProjectModel returned by the project_search function to facilitate the management of multiple Ecotaxa projects ?
That way, we could keep track of the project annotations and report the latest version in publications

A workaround is to use objectsApi with the function get_object_set(project_id,fields='obj.classif_when') and compute the max for each project (i.e. the timestamp of the most recent annotation) but it is relatively slow with multiple project ids

Thank you

**Comment by juliecoust** [comment]
This evolution shoud be done directly on ecotaxa_back repository.
